language: python
python:
    - "3.8"
install:
    - pip install -r requirements.txt

services:
    -docker
before_script:
    -docker build -t myimage .
script:
    -docker run -d --name dagpi -p 443:8080 -p 80:8080 -e PORT="8080" myimage
